# Generated by Django 5.1.2 on 2025-10-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("GOING", "Going"),
                    ("INTERESTED", "Interested"),
                    ("DECLINED", "Declined"),
                ],
                default="GOING",
                max_length=12,
            ),
        ),
    ]
