# Generated by Django 5.1.2 on 2025-10-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationdevice",
            name="platform",
            field=models.CharField(
                choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")],
                default="android",
                max_length=20,
            ),
        ),
    ]
