services:
  - type: web
    name: outvier-api
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: bash -lc "cd backend && gunicorn api.wsgi:application --bind 0.0.0.0:$PORT"
    postdeploy: bash -lc "cd backend && python manage.py migrate --noinput"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: CORS_ALLOW_ALL
        value: "True"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,outvier-api.onrender.com"
      - key: USE_SQLITE
        value: "False"
      - fromDatabase:
          name: outvier-db
          property: connectionString
          key: DATABASE_URL

databases:
  - name: outvier-db
    plan: free
