# Generated by Django 4.2.7 on 2025-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "outvier",
            "0002_achievement_goal_allow_mentorship_goal_current_value_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="teammatch",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Show this match to anonymous users"
            ),
        ),
    ]
