# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outvier', '0003_mentorevent_mentoreventregistration_usergroup_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='email_sent_created',
            field=models.BooleanField(default=False, help_text='Email notification sent for goal creation'),
        ),
        migrations.AddField(
            model_name='goal',
            name='email_sent_completed',
            field=models.BooleanField(default=False, help_text='Email notification sent for goal completion'),
        ),
        migrations.AddField(
            model_name='goal',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last reminder email sent', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Email notification sent'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When email was sent', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_failed',
            field=models.BooleanField(default=False, help_text='Email sending failed'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_failure_reason',
            field=models.TextField(blank=True, help_text='Reason for email failure', null=True),
        ),
    ]








