# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outvier', '0004_email_notification_enhancements'),
    ]

    operations = [
        # Create EmailLog model for tracking email notifications
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('email_type', models.CharField(choices=[('goal_created', 'Goal Created'), ('goal_completed', 'Goal Completed'), ('goal_reminder', 'Goal Reminder'), ('event_created', 'Event Created'), ('event_reminder', 'Event Reminder'), ('match_found', 'Match Found'), ('weekly_digest', 'Weekly Digest')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.goal')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.mentorevent')),
                ('related_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.teammatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        
        # Create UserMatchingPreference model
        migrations.CreateModel(
            name='UserMatchingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable automatic matching')),
                ('match_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual Only')], default='weekly', max_length=20)),
                ('preferred_match_types', models.JSONField(default=list, help_text='Preferred match types')),
                ('min_compatibility_score', models.PositiveIntegerField(default=6, help_text='Minimum compatibility score for matches')),
                ('max_matches_per_cycle', models.PositiveIntegerField(default=5, help_text='Maximum matches per matching cycle')),
                ('exclude_previous_matches', models.BooleanField(default=True, help_text='Exclude users from previous matches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Matching Preference',
                'verbose_name_plural': 'User Matching Preferences',
            },
        ),
        
        # Create GroupActivity model for tracking group activities
        migrations.CreateModel(
            name='GroupActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('meeting', 'Meeting'), ('discussion', 'Discussion'), ('collaboration', 'Collaboration'), ('milestone', 'Milestone'), ('celebration', 'Celebration')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('is_virtual', models.BooleanField(default=True)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_activities', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='outvier.usergroup')),
            ],
            options={
                'verbose_name': 'Group Activity',
                'verbose_name_plural': 'Group Activities',
                'ordering': ['-activity_date'],
            },
        ),
        
        # Create GroupActivityParticipation model
        migrations.CreateModel(
            name='GroupActivityParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_comments', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='outvier.groupactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_activity_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Activity Participation',
                'verbose_name_plural': 'Group Activity Participations',
                'unique_together': {('activity', 'user')},
            },
        ),
        
        # Add indexes for better performance
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_goal_user_status ON outvier_goal (user_id, is_completed, target_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_goal_user_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_mentorevent_start_date ON outvier_mentorevent (start_date, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_mentorevent_start_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_usergroup_type_status ON outvier_usergroup (group_type, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_usergroup_type_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_email_log_user_type ON outvier_emaillog (user_id, email_type, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_email_log_user_type;"
        ),
    ]
