# Generated by Django 4.2.7 on 2025-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outvier", "0005_comprehensive_features_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupactivity",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="groupactivity",
            name="group",
        ),
        migrations.AlterUniqueTogether(
            name="groupactivityparticipation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="groupactivityparticipation",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="groupactivityparticipation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usermatchingpreference",
            name="user",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="email_sent_completed",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="email_sent_created",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="last_reminder_sent",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="email_failed",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="email_failure_reason",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="email_sent",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="email_sent_at",
        ),
        migrations.AddField(
            model_name="teammatch",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Show this match to anonymous users"
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="related_events",
            field=models.ManyToManyField(
                blank=True, related_name="user_groups", to="outvier.mentorevent"
            ),
        ),
        migrations.DeleteModel(
            name="EmailLog",
        ),
        migrations.DeleteModel(
            name="GroupActivity",
        ),
        migrations.DeleteModel(
            name="GroupActivityParticipation",
        ),
        migrations.DeleteModel(
            name="UserMatchingPreference",
        ),
    ]
