# Generated by Django 4.2.7 on 2025-09-03 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=500)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("webinar", "Webinar"),
                            ("workshop", "Workshop"),
                            ("meetup", "Meetup"),
                            ("conference", "Conference"),
                            ("training", "Training"),
                            ("networking", "Networking"),
                            ("social", "Social Event"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("is_virtual", models.BooleanField(default=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("virtual_meeting_url", models.URLField(blank=True, null=True)),
                (
                    "virtual_meeting_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("requires_registration", models.BooleanField(default=True)),
                ("max_attendees", models.PositiveIntegerField(blank=True, null=True)),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "eventbrite_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("eventbrite_url", models.URLField(blank=True, null=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/covers/"
                    ),
                ),
                ("gallery", models.JSONField(default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("allow_comments", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("registration_count", models.PositiveIntegerField(default=0)),
                ("attendance_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("registration_message", models.TextField(blank=True, null=True)),
                ("dietary_requirements", models.TextField(blank=True, null=True)),
                ("accessibility_needs", models.TextField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("feedback_rating", models.PositiveIntegerField(blank=True, null=True)),
                ("feedback_comments", models.TextField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "db_table": "event_registrations",
                "ordering": ["-registered_at"],
                "unique_together": {("event", "user")},
            },
        ),
    ]
