# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='virtual_meeting_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_mentor_event',
            field=models.BooleanField(default=False, help_text='Event created by a mentor'),
        ),
        migrations.AddField(
            model_name='event',
            name='mentor_notes',
            field=models.TextField(blank=True, help_text='Special notes from mentor', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_mentees',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum mentees for this event', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Requires mentor approval to join'),
        ),
    ]
