# Generated by Django 5.1.2 on 2025-10-11 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="last_reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="reminder_channel",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("PUSH", "Push"),
                    ("EMAIL", "Email"),
                    ("BOTH", "Both"),
                ],
                default="NONE",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="reminder_repeat",
            field=models.CharField(
                choices=[("NONE", "None"), ("DAILY", "Daily"), ("WEEKLY", "Weekly")],
                default="NONE",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="timezone_str",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.CreateModel(
            name="GoalParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("EDITOR", "Editor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="VIEWER",
                        max_length=8,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="goals.goal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_participation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("goal", "user")},
            },
        ),
    ]
